name="df_single_pendulum_full"
dataset="video_single_pendulum_full"
batch_size=4
epochs=60
checkpointing_frequency=1000
val_every_n_epoch=101
val_batch_size=25
val_limit_batch=2
chunk_size=1
transition_type="forward-only"
resume=w50oju1e

CUDA_VISIBLE_DEVICES=0 python main.py \
    +name=${name} \
    dataset=${dataset} \
    experiment.training.batch_size=${batch_size} \
    experiment.training.max_epochs=${epochs} \
    experiment.training.checkpointing.every_n_train_steps=${checkpointing_frequency} \
    experiment.validation.val_every_n_epoch=${val_every_n_epoch} \
    experiment.tasks=["training","validation"] \
    experiment.validation.batch_size=${val_batch_size} \
    experiment.validation.limit_batch=${val_limit_batch} \
    +algorithm.metrics=["mse"] \
    algorithm.chunk_size=${chunk_size} \
    algorithm.diffusion.transition_type=${transition_type} \
    resume=${resume}