name="df_double_pendulum"
dataset="video_double_pendulum"
batch_size=3
epochs=150
checkpointing_frequency=10000
val_every_n_epoch=151
val_batch_size=20
val_limit_batch=2
chunk_size=30
transition_type="bi-gru"

CUDA_VISIBLE_DEVICES=1 python main.py \
    +name=${name} \
    dataset=${dataset} \
    experiment.training.batch_size=${batch_size} \
    experiment.training.max_epochs=${epochs} \
    experiment.training.checkpointing.every_n_train_steps=${checkpointing_frequency} \
    experiment.validation.val_every_n_epoch=${val_every_n_epoch} \
    experiment.tasks=["training","validation"] \
    experiment.validation.batch_size=${val_batch_size} \
    experiment.validation.limit_batch=${val_limit_batch} \
    +algorithm.metrics=["mse"] \
    algorithm.chunk_size=${chunk_size} \
    algorithm.diffusion.transition_type=${transition_type}