name="df_double_pendulum_latents"
dataset="video_double_pendulum_vae_latents"
batch_size=20
epochs=150
checkpointing_frequency=3000
val_every_n_epoch=1
val_batch_size=100
device=1

export PYTHONPATH="/data2/users/lr4617"
export CUDA_VISIBLE_DEVICES=${device}
CUDA_VISIBLE_DEVICES=${device} python main.py \
    +name=${name} \
    dataset=${dataset}\
    experiment.training.batch_size=${batch_size} \
    experiment.training.max_epochs=${epochs} \
    experiment.training.checkpointing.every_n_train_steps=${checkpointing_frequency} \
    experiment.validation.val_every_n_epoch=${val_every_n_epoch} \
    experiment.validation.batch_size=${val_batch_size} \
    experiment.use_callbacks=true \
    experiment.tasks=["training","validation"] \
    experiment.device=${device}\
    algorithm.metrics=["mse"] \
