name="df_three_body"
dataset="video_three_body"
batch_size=3
epochs=150
checkpointing_frequency=15000
val_every_n_epoch=151
val_batch_size=25

CUDA_VISIBLE_DEVICES=1 python main.py \
    +name=${name} \
    resume=94qmixi5 \
    dataset=${dataset}\
    experiment.training.batch_size=${batch_size} \
    experiment.training.max_epochs=${epochs} \
    experiment.training.checkpointing.every_n_train_steps=${checkpointing_frequency} \
    experiment.validation.val_every_n_epoch=${val_every_n_epoch} \
    experiment.validation.batch_size=${val_batch_size} \
    experiment.tasks=["training","validation"] \
    experiment.validation.batch_size=${val_batch_size} \
    algorithm.metrics=["mse"]